### ISSUE TITLE
Add link section

### ISSUE THREAD

**Issue by StefanJanssen95** [kogg/instant-logos#2886]
Most companies have guidelines in how to use a logo like: dont stretch it and a certain distance from other logos. Since these things are found on the page one downloads the logo most of the time it's still better to search yourself.

Add a link section where one can put a link to the guidelines for each logo.

**Comment by saiichihashimoto** [comment]
This was one of our initial concerns that we decided not to handle. In the cases where you'd want the branding guidelines, you wouldn't download the logo from our website; you'd have gone to their website already and be ready to go. That's not the use case we're aiming to solve. That use case would be solved better with a searchable directory of guidelines, not logos. If you're going to check the guidelines of each logo you want, then you'll never really download from us.

Our users enter the website knowing that they're going to be using the logos and are taking the responsibility of following the guidelines upon themselves, whether they've read them or not. I like the suggestion, but we've decided against this approach.
