### ISSUE TITLE
Kremlin

### ISSUE THREAD

**Issue by darkboutique** [kogg/instant-logos#3765]
Official kremlin logo

[kremlin.zip](https://github.com/kogg/instant-logos/files/166047/kremlin.zip)

**Comment by saiichihashimoto** [comment]
Thanks for your contribution!

We recently decided not to have our logo suggestions be in github; it became way too overwhelming! From now on, please suggest logos [directly on the website](http://instantlogosearch.com/?q=Kremlin). I've already suggested this logo through the interface, so I'm closing this issue.
