### ISSUE TITLE
No confirmation when suggesting logo

### ISSUE THREAD

**Issue by emilstahl** [kogg/instant-logos#3853]
Confirmation when suggestion/uploading a logo would be nice.

**Comment by StefanJanssen95** [comment]
That is indeed something that should be added.

**Comment by cameronrohani** [comment]
Hey guys, we'll be changing the pop up's copy in the next day or two to let users know that their logos need to be approved. Do you think we need more than this?

**Comment by emilstahl** [comment]
@cameronrohani When I uploaded a logo, there was no confirmation, popup etc.?

**Comment by StefanJanssen95** [comment]
I didnt get a popup either.

**Comment by saiichihashimoto** [comment]
So one good (bad?) thing we've done is that the website is caches for quite some time in your browser for more _instant_ loading times. You very well may have an old version cached.

![Screenshot of modal](http://i.imgur.com/isFtM1u.png)
You **should** be seeing what's in the screenshot when suggesting a logo. Let us know if this isn't happening for you! Screenshots or other context (ie console logs) would be greatly apprecaiated!
