### ISSUE TITLE
Update the logo directory when a logo is being approved

### ISSUE THREAD

**Issue by vbouchet31** [kogg/instant-logos#4352]
Is there any way to get the logo directory being updated on github when a logo is being approved on the website so github remains up-to-date. That would help to keep the project open.

Thanks,

**Comment by saiichihashimoto** [comment]
Thanks for the suggestion @vbouchet31! We curate all the logos on instantlogosearch for quality and accuracy. They only end up in github once we've deemed it acceptable.
