### ISSUE TITLE
SVG blocked

### ISSUE THREAD

**Issue by amatzen** [kogg/instant-logos#4354]
Chrome says that the server has blocked my access to the SVG file. It's not only 1 logo, it's multiple logos.

https://i.imgur.com/l9ZPF9d.png

**Comment by saiichihashimoto** [comment]
I can't understand that screenshot. What is that a screenshot of and what does it say?

**Comment by amatzen** [comment]
It's a Chrome Downloads section.
It says: "The server has denied you access to this resource" and then the link to the SVG file.

**Comment by saiichihashimoto** [comment]
Thanks for clarifying, @amatzen! We've been looking into this issue recently. Thanks for pointing it out!

**Comment by saiichihashimoto** [comment]
We've fixed this issue recently! Please try this again and let us know if you get the same issue.

Closing.
