### ISSUE TITLE
Logos

### ISSUE THREAD

**Issue by jwoertink** [kogg/instant-logos#569]
Hey, this is pretty awesome! I use SVG logos on my site https://namechk.com. I only have them in single colors because they're converted to a font, but if you'd like them I can zip them up, and send them all over.

**Comment by saiichihashimoto** [comment]
We'd love to include your logos! Our requirements for the logos are:
- They need to be svgs
- They either need to be uploaded through our website ([like you can see for OKCupid](http://instantlogosearch.com/?q=OKCupid)) or in git repo. If you have them in a git repo, go ahead and create an issue here with a link to them, so we can include them.

I'm going to close this issue and you can proceed whichever way makes more sense for you. Thanks!
